"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [("lessdrf-desktop/lib/python3.12/site-packages/streamlit/runtime", "./streamlit/runtime")]
DATA_FILES += [("lessdrf-desktop/lib/python3.12/site-packages/streamlit/static", "./streamlit/static")]
DATA_FILES += [("lessdrf-desktop/lib/python3.12/site-packages/st_aggrid/frontend", "./st_aggrid/frontend")]
DATA_FILES += [("lessdrf-desktop/lib/python3.12/site-packages/streamlit_tree_select/frontend", "./streamlit_tree_select/frontend")]
DATA_FILES += [("application", "./application")]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    packages=["pronto", "streamlit", "st_aggrid", "streamlit_tree_select","jsonschema","zipp", "openpyxl","altair", ]
)
